In [11]:
import pandas as pd

import os

os.listdir('C:/Users/user/Krishna/mncfc_crop_classification/data_files/new+old/new')

['Karera_Teh_Must_100_80.xlsx',
 'Karera_Teh_Wheat.xlsx',
 'Shivpuri_Teh_Must_100_100.xlsx',
 'Shivpuri_Teh_Wheat.xlsx']

In [5]:
import pandas as pd
  
# Read and store content
# of an excel file 
read_file = pd.read_excel (r'C:/Users/user/Krishna/mncfc_crop_classification/data_files/new+old/new/Shivpuri_Teh_Wheat.xlsx')
  
# Write the dataframe object
# into csv file
dp = read_file.to_csv (r'C:\Users\user\Documents\Crop_Spectral_Raw_datafiles\Crop_files_from_mncfc_CSV_format/Shivpuri_Teh_Wheat.csv', 
                  index = None,
                  header=True)
    
# read csv file and convert 
# into a dataframe object
#df = pd.DataFrame(pd.read_csv(dp))


# show the dataframe
dp

In [32]:
wheat_file = pd.read_csv(r'C:\Users\user\Documents\Crop_Spectral_Raw_datafiles\Crop_files_from_mncfc_CSV_format\Crop_MP_Sowing_2022.csv')

In [33]:
wheat_file

,FID,lat,long,Crop_Nam_1,STATE_NAME,DISTRICT,Oct_2FN,Nov_1FN,Nov_2FN,Dec_1FN,Dec_2FN,Jan_1FN,Jan_2FN,Feb_1Fn,Feb_2Fn,Mar_1Fn,Mar_2Fn,Apr_1fn
0,66,26.275699,77.317284,2 Mustard,Madhya Pradesh,MORENA,117,130,183,186,183,188,184,184,165,131,165,180
1,819,26.235858,77.446783,2 Mustard,Madhya Pradesh,MORENA,121,151,190,191,188,186,189,187,168,138,149,171
2,1219,24.970808,75.246897,2 Mustard,Madhya Pradesh,NIMACH,142,174,178,181,180,177,163,129,135,138,145,171
3,1252,24.901777,75.255574,2 Mustard,Madhya Pradesh,NIMACH,141,155,166,173,178,178,175,176,157,143,143,125
4,1253,24.901773,75.255630,2 Mustard,Madhya Pradesh,NIMACH,141,155,166,173,178,178,175,176,157,143,143,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1576,8030,24.073376,75.698507,pulses,Madhya Pradesh,MANDSAUR,136,120,172,181,175,163,149,135,117,112,111,1
1577,2135,22.309621,79.280410,pulses,Madhya Pradesh,CHHINDWARA,122,144,159,162,166,153,132,116,114,115,111,1
1578,3190,23.886489,76.148996,2 Mustard,Madhya Pradesh,AGAR-MALWA,125,117,143,159,170,170,167,165,137,121,112,1
1579,3191,23.886476,76.148988,2 Mustard,Madhya Pradesh,AGAR-MALWA,125,117,143,159,170,170,167,165,137,121,112,1
1580,6128,23.711413,76.539161,2 Mustard,Madhya Pradesh,RAJGARH,131,112,151,169,178,183,180,174,147,119,111,1

In [3]:
dp

In [36]:
from sqlalchemy import create_engine
import psycopg2
import pandas as pds

if __name__ == '__main__':
    # Number of processes to run in parallel
        
    #DB details
    host = 'localhost'
    port = '5432'
    database = 'postgis_33'
    user = 'postgres'
    password = 'wadhwanikdss'

    conn = f"postgresql://{user}:{password}@{host}:{port}/{database}"
    engine = create_engine(conn)
    
#Importing csv table from local machine
dataFrame = pds.read_csv(r'C:\Users\user\Documents\Crop_Spectral_Raw_datafiles\Crop_files_from_mncfc_CSV_format\Wheat_MP_Sowing_2022.csv')
postgreSQLTable         = "Wheat_MP_Sowing_2022"

# Creating the table in postgresql according to the dataframe imported as csv
postgreSQLConnection     = engine.connect()

try:

    frame           = dataFrame.to_sql(postgreSQLTable, postgreSQLConnection, if_exists='fail', schema="crop_signature_bronze")

except Exception as ex:  

    print(ex)

else:

    print("PostgreSQL Table %s has been created successfully."%postgreSQLTable)
    
finally:

    postgreSQLConnection.close()
    
    
engine.dispose()

PostgreSQL Table Wheat_MP_Sowing_2022 has been created successfully.

In [12]:
pwd

'/wadhwani_kdss/Priyanka/Priyanka'

In [1]:
import zipfile as zp
import geopandas as gp
import pandas as pd
import numpy as np
import shutil
import os
from IPython.display import clear_output, display
import time
import concurrent.futures as cf

In [13]:
# Code for crawling the shared drive
lst = []
for path, currentDirectory, files in os.walk(r'/mnt/ncfc data/scratch/FASAL/GT_Refinement/Refined_GT_data'):
    for file in files:
        lst.append(os.path.join(path, file))

In [14]:
lst[0].split('\\')[-1]

IndexError: list index out of range

In [11]:
lst

[]

In [4]:
df = pd.DataFrame(lst, columns=['File_path'])
df['File_Name'] = df['File_path'].apply(lambda path:path.split('\\')[-1])
df['Ext'] = df['File_Name'].apply(lambda path:path.split('.')[-1])
df['File_Name'] = df['File_Name'].apply(lambda path:path.split('.')[0:1])
df[df['Ext'] == 'shp']

,File_path,File_Name,Ext
5,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],shp
13,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Jh_K_Rice_Refined_GT_2022_23],shp
21,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Kharif_Rice _shifted GT ],shp
26,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[kharif_rice],shp
33,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[kharif_rice2022],shp
...,...,...,...
745,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[k_Rice_Shifted_2020-21],shp
753,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[K_rice_Shifted2021-22],shp
761,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[K_rice_GT_2022-23],shp
769,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted_GT_must],shp
777,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],shp

In [5]:
start = 1
df.insert(0, 'ID', range(start, start + df.shape[0]))
df

,ID,File_path,File_Name,Ext
0,1,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],cpg
1,2,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],dbf
2,3,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],prj
3,4,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],sbn
4,5,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],sbx
...,...,...,...,...
775,776,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],sbn
776,777,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],sbx
777,778,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],shp
778,779,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],shx
779,780,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],xml

In [6]:
df['unique_file_name']  = df['File_Name'].astype(str) + '_' + df['ID'].astype(str)
df

,ID,File_path,File_Name,Ext,unique_file_name
0,1,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],cpg,['Assam_Paddy_GT_2022']_1
1,2,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],dbf,['Assam_Paddy_GT_2022']_2
2,3,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],prj,['Assam_Paddy_GT_2022']_3
3,4,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],sbn,['Assam_Paddy_GT_2022']_4
4,5,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Assam_Paddy_GT_2022],sbx,['Assam_Paddy_GT_2022']_5
...,...,...,...,...,...
775,776,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],sbn,['Shifted Rice GT']_776
776,777,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],sbx,['Shifted Rice GT']_777
777,778,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],shp,['Shifted Rice GT']_778
778,779,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],shx,['Shifted Rice GT']_779
779,780,\\192.168.1.152\ncfc data\scratch\FASAL\GT_Ref...,[Shifted Rice GT],xml,['Shifted Rice GT']_780

In [7]:
list(df.columns)

['ID', 'File_path', 'File_Name', 'Ext', 'unique_file_name']

In [6]:
dp = df[df['Ext'] == 'shp']

In [9]:
df.to_csv(r'C:\Users\user\Documents\Crop_Spectral_Raw_datafiles\Crop_files_from_mncfc_CSV_format\Old_years_files_path.csv')

In [14]:
from sqlalchemy import create_engine
import geopandas as gp
import multiprocessing
import zipfile as zp
import pandas as pd
import numpy as np
import shutil
import os
from IPython.display import clear_output, display
import time
import concurrent.futures as cf
import psycopg2
from datetime import datetime
import geoalchemy2


df = pd.read_csv(r'C:\Users\user\Documents\Crop_Spectral_Raw_datafiles\Crop_files_from_mncfc_CSV_format\Old_years_files_path.csv')
shp_df = df[df.Ext == 'shp']
shp_df.head()

def shp_zip_read(full_path):
    os.makedirs(r"E:\New folder", exist_ok=True)
    zip_file_path = full_path.split('.zip\\')[0] + '.zip'
    shp_file_path = full_path.split('.zip\\')[1]
    print(shp_file_path)
    archive = zp.ZipFile(zip_file_path)
    if '/' not in shp_file_path:
        for file in archive.namelist():
            if '/' not in file:
                archive.extract(file, r"E:\New folder")
        shp_folder_path = ''
    else:
        shp_folder_path = '/'.join(shp_file_path.split('/')[:-1])+'/'
        for file in archive.namelist():
            if file.startswith(shp_folder_path):
                archive.extract(file, r"E:\New folder")
    gdf = gp.read_file("E:\\New folder\\{}".format(shp_folder_path))
    shutil.rmtree(r'E:\New folder', ignore_errors=True)
    return gdf

def shape_file_dump(file_name, file_path, engine):
    
    #connection = engine.connect()
    
    # Reading the shape file
    if '.zip' in file_path:
        gdf = shp_zip_read(file_path)
    else:
        gdf = gp.read_file(file_path)

    #Import shapefile to databse
    #print(file_name)
    gdf.to_postgis(name=file_name, con=engine, schema="crop_signature_bronze")

    
# Deriving a unique file name to create table in the database 




if __name__ == '__main__':
    # Number of processes to run in parallel
    num_processes = multiprocessing.cpu_count()
        
    #DB details
    host = 'localhost'
    port = '5432'
    database = 'postgis_33'
    user = 'postgres'
    password = 'wadhwanikdss'

    conn = f"postgresql://{user}:{password}@{host}:{port}/{database}"
    engine = create_engine(conn)
    

    j = 0
    
    
      
for i in range(shp_df.shape[0]):
    #initialising empty data frame to store errors
    df = pd.DataFrame(columns=['iteration','unique_file_name', 'file_path', 'error', 'error_type']) 
    
    
    if '.zip' in shp_df.File_path.iloc[i]:  
        continue
    
    file_present = False
    #print('waiting for shared drive access ')
    while file_present == False:
        j=j+1
        file_check = r'\\192.168.1.151\ncfc_data3\CHAMAN\mango\East Champaran\analysis\merge_mango_echamparan.shp'
        if os.path.exists(file_check) or os.path.exists(file_check.replace(".151",".152")):
            print(f'Executing {i}st file')
            File_path = shp_df.File_path.iloc[i]
            
            if os.path.exists(File_path) == False:
                File_path = File_path.replace(".151",".152") 
            
            
            


            try:
                 shape_file_dump(shp_df.unique_file_name.iloc[i], File_path, engine)
        #print(shp_df.unique_file_name.iloc[i])

            except Exception as e:
                        error=e
                        print(error, File_path)
             #if 'Identifier' not in str(error):
                        df.loc[len(df.index)] = [i,shp_df.unique_file_name.iloc[i], File_path, error, type(error)]

            df.to_csv(f"C:/Users/user/Documents/Crop_Spectral_Raw_datafiles/Crop_files_from_mncfc_CSV_format/Old_years_files_path_UPLOAD_TRACKER.csv" , mode='a', index=False, header=False)

                #if type(error) == fiona.errors.DriverError:
            file_present = True
            break 
            
        else:
            print('waiting for shared drive access ') 
            time.sleep(40)
    if j == 1000:
        time.sleep(3)
        clear_output(wait=True)
        display('Output cleared')
        print(i)
        j = 0     


print("Data dumped successfully into the PostGIS database.")
    
engine.dispose()

Executing 0st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\Assam_Paddy_GT_2022.shp
Executing 1st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\Jh_K_Rice_Refined_GT_2022_23.shp
Executing 2st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\Kharif_Rice _shifted GT .shp
Executing 3st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\kharif_rice.shp
Executing 4st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\kharif_rice2022.shp
Executing 5st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\Krice_2022_23.shp
Executing 6st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\K_rice_GT_2022-23.shp
Executing 7st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\Orissa_Kharif_GT_2022_fine.shp
Executing 8st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\Paddy_2022.shp
Executing 9st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\paddy_2022_23.shp
Executing 10st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\paddy_2022_up.shp
Executing 11st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Andra Pradesh\Cotton\2022-2023\Refined_file\Cotton.shp
Executing 12st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Andra Pradesh\Tur\2022\Refined_File\Tur_AP_refined_2022-2023.shp
Executing 13st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Andra Pradesh\Tur\2022\Total_data\Tur_Andhra_Pradesh.shp
Executing 14st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Assam\Kharif_Rice\2022_2023\Assam_Paddy_GT_2022.shp
Executing 15st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\Jute\2022_23\jute_2022.shp
Executing 16st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\K_Rice\2018\Krice_2018.shp
Executing 17st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\K_Rice\2020-21\paddy_2020_21.shp
Executing 18st file

Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\K_Rice\2022-23\paddy_2022_23.shp
Executing 19st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\Mustard\2022-2023\Bihar_mustard_gt.shp
Executing 20st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\Wheat\2017-18\Wheat_2018.shp
Executing 21st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\Wheat\2020-21\wheat_2020_21.shp
Executing 22st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\Wheat\2021-22\Bihar_Wheat_2021-22.shp
Executing 23st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Bihar\Wheat\2022-23\Wheat_2022_23.shp
Executing 24st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Chhattisgarh\Kharif_Rice\2022_23\Kharif_Rice _shifted GT .shp
Executing 25st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Gujarat\Cotton\2022_2023\Cotton_GT_Refined_2022-23.shp
Executing 26st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Gujarat\Mustard\2022_2023\GT_Mustard_refined.shp
Executing 27st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Gujarat\Sugarcane\2022_2023\sugarcane_GT.shp
Executing 28st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Gujarat\Wheat\2022_2023\GT_Wheat_refined.shp
Executing 29st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Haryana\2022_23\Cotton\Cotton_2022_RefinedGT.shp
Executing 30st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Haryana\2022_23\KHARIF_RICE\Paddy_2022.shp
Executing 31st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Haryana\2022_23\MUSTARD\2022-2023\MUSTARD_GT_2022_2023_CORRECTED.shp
Executing 32st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Haryana\2022_23\WHEAT\2022-2023\WHEAT_GT_2022_2023_CORRECTED.shp
Executing 33st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Himachal\Wheat\2021\Wheat.shp
Executing 34st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Himachal\Wheat\2022\Wheat_2022.shp
Executing 35st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Jharkhand\Kharif Rice\2021-22\Jh_Refined_Rice_GT_2021-22.shp
Executing 36st file

Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Jharkhand\Kharif Rice\2022-23\Jh_K_Rice_Refined_GT_2022_23.shp
Executing 37st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Jharkhand\Kharif Rice\2022-23\Other GT\Jh_Other_Crop_GT_2022_23.shp
Executing 38st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Jharkhand\Kharif Rice\2022-23\Other GT\Jh_Total_GT_2022_23.shp
Executing 39st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Karnataka\Cotton\2022-2023\Cotton_2022-23.shp
Executing 40st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Karnataka\Kharif_Rice\2022-2023\Krice_2022_23.shp
Executing 41st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Karnataka\Rabi Pulses\2022-2023\RabiPulses_2022_23.shp
Executing 42st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Karnataka\Rabi Rice\2022-2023\Rabi_rice_2022-23.shp
Executing 43st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Karnataka\Rabi Sorghum\2022-2023\Rabi_Sorghum_2022-23.shp
Executing 44st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Karnataka\Sugarcane\2022_2023\GT_KR_Sugarcane_2022-23.shp
Executing 45st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Karnataka\Tur\2022_2023\Tur_2022-23.shp
Executing 46st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\MadhyaPradesh\Gram\2022-23\Gram.shp
Executing 47st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\MadhyaPradesh\Mustard\2022-2023\Mustard.shp
Executing 48st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\MadhyaPradesh\Rabi pulses\2022-23\Pulses.shp
Executing 49st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\MadhyaPradesh\Wheat\2022-2023\Wheat.shp
Executing 50st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Cotton\2019-2020\Cotton1.shp
Executing 51st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Cotton\2020-2021\Cotton.shp
Executing 52st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Cotton\2021-2022\Cotton.shp
Executing 53st file

Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Cotton\2022-2023\Cotton.shp
Executing 54st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sorgum\2019-2020\Sorghum_GT_2019.shp
Executing 55st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sorgum\2020-2021\Sorghum.shp
Executing 56st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sorgum\2021-2022\Sorgum.shp
Executing 57st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sorgum\2022-2023\Sorgum.shp
Executing 58st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sugarcane\2019-2020\Sugarcane1.shp
Executing 59st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sugarcane\2020-2021\Sugarcane.shp
Executing 60st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sugarcane\2021-2022\Sugarcane.shp
Executing 61st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Maharashtra\Sugarcane\2022-2023\Sugarcane.shp
Executing 62st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Orissa\GT refined for Paddy 2022\Orissa_Kharif_GT_2022_fine.shp
Executing 63st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Rajasthan\Mustard\2020-2021\2020_21mustard_gt.shp
Executing 64st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Rajasthan\Mustard\2021-2022\2021_22MUSTARD.shp
Executing 65st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Rajasthan\Mustard\2022-2023\Mustard_GT_final.shp
Executing 66st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Rajasthan\Pulses\2022-2023\final_gt.shp
Executing 67st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Rajasthan\Wheat\2020_21\gt_wheat_2020_21.shp
Executing 68st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Rajasthan\Wheat\2021_22\gt_wheat_2021_22.shp
Executing 69st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Rajasthan\Wheat\2022-2023\Wheat_GT_Final.shp
Executing 70st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Tamil Nadu\Kharif Rice\2022-2023\kharif_rice.shp
Executing 71st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Cotton\2018-2019\Cotton_2018.shp

Executing 72st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Cotton\2020-2021\Cotton.shp
Executing 73st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Cotton\2021-2022\cotton_22.shp
Executing 74st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Cotton\2022-2023\cotton_2022_23.shp
Executing 75st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Kharif Rice\2018-2019\Kharif_Rice_2018.shp
Executing 76st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Kharif Rice\2020-2021\Kharif_Rice_2020_21.shp
Executing 77st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Kharif Rice\2021-2022\kharif_rice2022.shp
Executing 78st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Rabi Rice\2018-2019\Rabi_Rice_2018.shp
Executing 79st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Rabi Rice\2020-2021\R_Rice_2020_21_Final.shp
Executing 80st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Rabi Rice\2021-2022\Rabi_rice_2021_22.shp
Executing 81st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Rabi Rice\2022-2023\Rabi_rice_2022_23.shp
Executing 82st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Red Gram\2020-2021\Red_Gram.shp
Executing 83st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Telangana\Red Gram\2022-2023\Red_gram.shp
Executing 84st file
Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) \\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\Uttarakhand\Sugarcane\2019_20\Sugarcane.shp
Executing 85st file

KeyboardInterrupt:

In [29]:
shp_df.shape

(102, 5)

In [31]:
decoded_path = shortener.decode_shortened_path('963ba1ab')
print(decoded_path)

\\192.168.1.152\ncfc data\scratch\FASAL\GT_Refinement\Refined_GT_data\All India K Rice GT 2022\Kharif_Rice _shifted GT .shp

In [13]:
!pip install geoalchemy2

Collecting geoalchemy2
  Downloading GeoAlchemy2-0.14.0-py3-none-any.whl (54 kB)
                                              0.0/54.0 kB ? eta -:--:--
     ---------------------------------------- 54.0/54.0 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: SQLAlchemy>=1.4 in c:\users\user\miniconda3\envs\mncfc\lib\site-packages (from geoalchemy2) (1.4.39)
Requirement already satisfied: packaging in c:\users\user\miniconda3\envs\mncfc\lib\site-packages (from geoalchemy2) (22.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\miniconda3\envs\mncfc\lib\site-packages (from SQLAlchemy>=1.4->geoalchemy2) (2.0.1)
Installing collected packages: geoalchemy2
Successfully installed geoalchemy2-0.14.0